
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: banking-ingress
  namespace: banking
  labels:
    app.kubernetes.io/name: banking-frontend
    app.kubernetes.io/part-of: dtb-banking-portal
    app.kubernetes.io/component: frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
   
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-Frame-Options SAMEORIGIN;
      add_header X-Content-Type-Options nosniff;
      add_header Referrer-Policy strict-origin-when-cross-origin;
spec:
  ingressClassName: nginx
  rules:
    - host: banking.local
      http:
        paths:
          
          - path: /
            pathType: Prefix
            backend:
              service:
                name: banking-frontend
                port:
                  name: http
