
apiVersion: v1
kind: Service
metadata:
  name: banking-frontend
  namespace: banking
  labels:
    app.kubernetes.io/name: banking-frontend
    app.kubernetes.io/part-of: dtb-banking-portal
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: banking-frontend
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
