
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: push-trigger-binding
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/part-of: dtb-banking-portal
    app.kubernetes.io/component: tekton-trigger
spec:
  params:
    - name: git-url
      value: $(body.repository.clone_url)
    - name: git-revision
      value: $(body.after)
    - name: git-branch
      value: $(body.ref)
    - name: image-tag
      value: $(body.after)

---

apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: pr-trigger-binding
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/part-of: dtb-banking-portal
    app.kubernetes.io/component: tekton-trigger
spec:
  params:
    - name: git-url
      value: $(body.pull_request.head.repo.clone_url)
    - name: git-revision
      value: $(body.pull_request.head.sha)
    - name: git-branch
      value: $(body.pull_request.head.ref)
    - name: image-tag
      value: $(body.pull_request.head.sha)
