apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-pipeline-sa
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/part-of: dtb-banking-portal
    app.kubernetes.io/component: tekton-rbac
secrets:
  - name: regcred
  - name: git-credentials
