apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-secret
  namespace: banking
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/part-of: dtb-banking-portal
    app.kubernetes.io/component: database
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-cluster-secret-store
    kind: ClusterSecretStore

  target:
    name: mongodb-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: mongodb
          app.kubernetes.io/part-of: dtb-banking-portal
          app.kubernetes.io/component: database

  data:
    - secretKey: MONGO_ROOT_USER
      remoteRef:
        key: secret/data/banking/mongodb
        property: root_user

    - secretKey: MONGO_ROOT_PASSWORD
      remoteRef:
        key: secret/data/banking/mongodb
        property: root_password

    - secretKey: MONGO_APP_USER
      remoteRef:
        key: secret/data/banking/mongodb
        property: app_user

    - secretKey: MONGO_APP_PASSWORD
      remoteRef:
        key: secret/data/banking/mongodb
        property: app_password
