apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: banking
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/part-of: dtb-banking-portal
    app.kubernetes.io/component: database
  annotations:
    managed-by: external-secrets
type: Opaque
stringData:
  MONGO_ROOT_USER: "root"
  MONGO_ROOT_PASSWORD: "CHANGE_ME_ROOT"
  MONGO_APP_USER: "app_user"
  MONGO_APP_PASSWORD: "CHANGE_ME_APP"
