
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: banking
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/part-of: dtb-banking-portal
    app.kubernetes.io/component: database
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: database
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: banking
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/part-of: dtb-banking-portal
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: database
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
      protocol: TCP
