apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dtb-banking-portal
  namespace: argocd
  labels:
    app.kubernetes.io/name: dtb-banking-portal
    app.kubernetes.io/part-of: dtb-banking-portal
    app.kubernetes.io/managed-by: argocd-init-script
  annotations:
    app.kubernetes.io/polling-interval: "1800s"
    argocd.argoproj.io/sync-wave: "0"
    argocd-image-updater.argoproj.io/image-list: >-
      backend=muretimiriti/dtb-project-backend,frontend=muretimiriti/dtb-project-frontend
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    argocd-image-updater.argoproj.io/frontend.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default

  source:
    repoURL: "${REPO_URL}"
    targetRevision: HEAD
    path: manifests/k8s
    kustomize:
      images:
        - muretimiriti/dtb-project-backend
        - muretimiriti/dtb-project-frontend

  destination:
    server: https://kubernetes.default.svc
    namespace: banking

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1config
