apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secret
  namespace: banking
  labels:
    app.kubernetes.io/name: banking-backend
    app.kubernetes.io/part-of: dtb-banking-portal
    app.kubernetes.io/component: backend
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  # Refresh every 1 hour — Vault token rotation and secret rotation are picked up automatically
  refreshInterval: 1h

  secretStoreRef:
    name: vault-cluster-secret-store
    kind: ClusterSecretStore

  target:
    name: backend-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: banking-backend
          app.kubernetes.io/part-of: dtb-banking-portal
          app.kubernetes.io/component: backend

  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: secret/data/banking/backend
        property: jwt_secret

    - secretKey: MONGO_APP_PASSWORD
      remoteRef:
        key: secret/data/banking/mongodb
        property: app_password
