
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: banking
  labels:
    app.kubernetes.io/name: banking-backend
    app.kubernetes.io/part-of: dtb-banking-portal
    app.kubernetes.io/component: backend
  annotations:
    managed-by: external-secrets
type: Opaque
stringData:
  JWT_SECRET: "_RANDOM_STRING"   
  MONGO_APP_PASSWORD: "MONGO_APP_PASSWORD"              
