apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-workspace-pvc
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/part-of: dtb-banking-portal
    app.kubernetes.io/component: tekton-workspace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
